### ISSUE TITLE
Error while running the training script.

### ISSUE THREAD

**Issue by LarrySil** [AWF-GAUG/TreeCrownDelineation#12]
Hi,
I get an error like this when trying to run the training: 

- Traceback (most recent call last):
-   File "c:\TreeCrownDelineation\TreeCrownDelineation\examples\training_example.py", line 88, in <module>
-     trainer.fit(model, data)
-   File "C:\Users\samul\Anaconda\envs\TCD\Lib\site-packages\pytorch_lightning\trainer\trainer.py", line 543, in fit
-     call._call_and_handle_interrupt(
-   File "C:\Users\samul\Anaconda\envs\TCD\Lib\site-packages\pytorch_lightning\trainer\call.py", line 44, in _call_and_handle_interrupt
-     return trainer_fn(*args, **kwargs)
-            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
-   File "C:\Users\samul\Anaconda\envs\TCD\Lib\site-packages\pytorch_lightning\trainer\trainer.py", line 579, in _fit_impl
-     self._run(model, ckpt_path=ckpt_path)
-   File "C:\Users\samul\Anaconda\envs\TCD\Lib\site-packages\pytorch_lightning\trainer\trainer.py", line 948, in _run
-     call._call_setup_hook(self)  # allow user to set up LightningModule in accelerator environment
-     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
-   File "C:\Users\samul\Anaconda\envs\TCD\Lib\site-packages\pytorch_lightning\trainer\call.py", line 94, in _call_setup_hook
-     _call_lightning_datamodule_hook(trainer, "setup", stage=fn)
-   File "C:\Users\samul\Anaconda\envs\TCD\Lib\site-packages\pytorch_lightning\trainer\call.py", line 181, in _call_lightning_datamodule_hook
-     return fn(*args, **kwargs)
-            ^^^^^^^^^^^^^^^^^^^
- TypeError: InMemoryDataModule.setup() got an unexpected keyword argument 'stage'

Tried adding the "stage" argument to the setup function, but this does not seem to fix the issue.

**Comment by maxfreu** [comment]
Should be fixed now, please try again. Also, you can format code into code blocks by using triple backticks ``` before and after the code or error message.

**Comment by LarrySil** [comment]
This still seems to get the same error as above, even with the stage = None added to the setup. Could this be an issue with the pytorch version? I'm running 2.4.0

**Comment by maxfreu** [comment]
Stupid question, but are you sure that you are running the updated code? You can run your code in a debugger (e.g. in pycharm) to see which code is called and why it fails.
