### ISSUE TITLE
Versions of libraries

### ISSUE THREAD

**Issue by efukatsu** [AWF-GAUG/TreeCrownDelineation#4]
Hello,

I appreciate the good work of this project.

I tried training for my own dataset, but I couldn't execute the script "training_example.py", probably because of the inconsistency of the version of libraries.

For example, I obtained following error with pytorch_lightning 2.0.0:
"Traceback (most recent call last):
  File "TreeCrownDelineation/examples/training_example.py", line 82, in <module>
    trainer = Trainer(gpus=gpus,
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/utilities/argparse.py", line 69, in insert_env_defaults
    return fn(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'gpus'"

When I changed the version of pytorch_lightning to 1.9.4, I obtained following error:
"Traceback (most recent call last):
  File "TreeCrownDelineation/examples/training_example.py", line 82, in <module>
    trainer = Trainer(gpus=gpus,distributed_backend=backend,
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/utilities/argparse.py", line 348, in insert_env_defaults
    return fn(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'distributed_backend'"

I'll be happy If you show the version list by "pip3 list"  in your executable environment.

**Comment by maxfreu** [comment]
I added my conda environment.yaml for reference. It is an organically grown mess. Sorry for that. I'll try to find the time to put together an environment that works with a reasonable package manager.

**Comment by maxfreu** [comment]
Oh and here is the pip3 output. It should suffice to install the right versions of pytorch, pytorch lightning, gdal and xarray.

```
Package                     Version
--------------------------- ------------
absl-py                     1.0.0
affine                      2.3.0
aiohttp                     3.8.1
aiosignal                   1.2.0
albumentations              1.1.0
async-timeout               4.0.2
attrs                       21.2.0
backcall                    0.2.0
Bottleneck                  1.3.2
cachetools                  4.2.4
certifi                     2021.10.8
charset-normalizer          2.0.10
click                       7.1.2
click-plugins               1.1.1
cligj                       0.7.2
cloudpickle                 2.0.0
cycler                      0.11.0
cytoolz                     0.11.0
dask                        2021.10.0
decorator                   5.1.0
efficientnet-pytorch        0.6.3
entrypoints                 0.3
Fiona                       1.8.13.post1
fonttools                   4.25.0
frozenlist                  1.2.0
fsspec                      2021.10.1
future                      0.18.2
GDAL                        3.0.2
google-auth                 2.3.3
google-auth-oauthlib        0.4.6
grpcio                      1.43.0
hyperopt                    0.2.5
idna                        3.3
imagecodecs                 2021.8.26
imageio                     2.9.0
importlib-metadata          4.10.1
ipykernel                   5.3.4
ipython                     7.25.0
jedi                        0.18.0
joblib                      1.1.0
jupyter-client              7.0.6
jupyter-core                4.9.1
kiwisolver                  1.3.1
locket                      0.2.1
Markdown                    3.3.6
matplotlib                  3.5.0
matplotlib-inline           0.1.2
mkl-fft                     1.3.1
mkl-random                  1.2.2
mkl-service                 2.4.0
multidict                   5.2.0
munch                       2.5.0
munkres                     1.1.4
nest-asyncio                1.5.1
networkx                    2.6.3
numexpr                     2.7.3
numpy                       1.21.2
oauthlib                    3.1.1
olefile                     0.46
opencv-python-headless      4.5.5.62
packaging                   21.3
pandas                      1.3.4
parso                       0.8.2
partd                       1.2.0
pexpect                     4.8.0
pickleshare                 0.7.5
Pillow                      8.4.0
pip                         21.2.4
pretrainedmodels            0.7.4
prompt-toolkit              3.0.20
protobuf                    3.19.3
psutil                      5.8.0
ptyprocess                  0.7.0
pyasn1                      0.4.8
pyasn1-modules              0.2.8
pyDeprecate                 0.3.1
Pygments                    2.10.0
pymongo                     3.12.0
pyparsing                   3.0.4
pyproj                      3.3.0
python-dateutil             2.8.2
pytorch-lightning           1.2.3
pytz                        2021.3
PyWavelets                  1.1.1
PyYAML                      6.0
pyzmq                       22.3.0
qudida                      0.0.4
rasterio                    1.1.2
requests                    2.27.1
requests-oauthlib           1.3.0
rioxarray                   0.10.0
rsa                         4.8
scikit-image                0.18.1
scikit-learn                1.0.2
scipy                       1.7.1
segmentation-models-pytorch 0.2.0
setuptools                  58.0.4
Shapely                     1.7.1
sip                         4.19.13
six                         1.16.0
snuggs                      1.4.7
tensorboard                 2.7.0
tensorboard-data-server     0.6.1
tensorboard-plugin-wit      1.8.1
threadpoolctl               3.0.0
tifffile                    2021.7.2
timm                        0.4.12
toolz                       0.11.2
torch                       1.10.1
torchmetrics                0.7.0
torchvision                 0.11.2
tornado                     6.1
tqdm                        4.62.3
traitlets                   5.1.1
treecrowndelineation        0.1.0
typing-extensions           3.10.0.2
urllib3                     1.26.8
wcwidth                     0.2.5
Werkzeug                    2.0.2
wheel                       0.37.0
xarray                      0.17.0
yarl                        1.7.2
zipp                        3.7.0
```

**Comment by maxfreu** [comment]
Just updated the training example, to work with newer pytorch lightning versions. Let me know if it still doesn't work.
